USE [bazaRadova];
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;
INSERT INTO [dbo].[RadAutor]([IDRad], [IDAutor])
SELECT 10, 1 UNION ALL
SELECT 10, 2 UNION ALL
SELECT 11, 3 UNION ALL
SELECT 11, 4 UNION ALL
SELECT 12, 5
COMMIT;
RAISERROR (N'[dbo].[RadAutor]: Insert Batch: 1.....Done!', 10, 1) WITH NOWAIT;
GO

