USE [bazaRadova];
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

BEGIN TRANSACTION;
INSERT INTO [dbo].[RadKategorija]([RadID], [KatID])
SELECT 1, 1 UNION ALL
SELECT 1, 3 UNION ALL
SELECT 2, 1 UNION ALL
SELECT 2, 2 UNION ALL
SELECT 2, 4 UNION ALL
SELECT 3, 1 UNION ALL
SELECT 3, 2 UNION ALL
SELECT 3, 4 UNION ALL
SELECT 4, 1 UNION ALL
SELECT 4, 4 UNION ALL
SELECT 5, 1 UNION ALL
SELECT 5, 4 UNION ALL
SELECT 6, 1 UNION ALL
SELECT 6, 4 UNION ALL
SELECT 7, 3 UNION ALL
SELECT 8, 1 UNION ALL
SELECT 9, 1 UNION ALL
SELECT 10, 1 UNION ALL
SELECT 11, 1 UNION ALL
SELECT 12, 2
COMMIT;
RAISERROR (N'[dbo].[RadKategorija]: Insert Batch: 1.....Done!', 10, 1) WITH NOWAIT;
GO

